name: version-update
on:
  push:
    paths:
      - 'pyproject.toml'
      - '.github/workflows/version-update.yml'

jobs:
  version-update:
    runs-on: ubuntu-latest
    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the
        # added or changed files to the repository.
        contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: checkout
      uses: actions/checkout@v6
    - name: uv-install
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: uv-sync-minimal
      run: uv sync --no-dev
    - name: Get pompon version
      # from pompon import __version__; print(__version__)
      id: get_version
      run: echo "version=$(uv run python -c 'from pompon import __version__; print(__version__)')" >> $GITHUB_OUTPUT
    - name: Update README.md
      # rename like this: v0.1.10 -> v0.1.11
      run: sed -i "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/v${{ steps.get_version.outputs.version }}/g" README.md
    - name: Commit and push
      continue-on-error: true
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README.md"
        git push
